version: '3.3'
services:
    grafana:
        image: grafana
        container_name: grafana_c
        ports:
            - '3000:3000'
#        environment:
#            - "GF_SECURITY_ADMIN_PASSWORD:[YOUR_PASSWORD]"
        restart: always
        volumes:
            - 'grafana-data:/var/lib/grafana'
            - 'grafana-config:/etc/grafana'

    influxdb:
        image: influxdb
        container_name: influxdb_c
        ports:
            - '8086:8086'
        environment:
            - "INFLUXDB_DB=TelegrafDB"
        restart: always
        volumes:
            - 'influxdb-data:/var/lib/influxdb'

volumes:
    grafana-data:
    grafana-config:
    influxdb-data:
