version: '3.3'
services:
    db:
        image: 'mysql:5.7'
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: testos
        container_name: sf_app_db
        volumes:
            - 'db_data:/var/lib/mysql'
        restart: always
        ports:
            - '3306:3306'

    sf_app:
        image: sf_app
        container_name: sf_app_c
        ports:
            - '3569:80'
        restart: always
        volumes:
            - '[YOUR APP FULL PATH]:/var/www/gitlab-sf/'

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: testos
        container_name: sf_app_phpmyadmin
        ports:
            - '9658:80'
        restart: always
        links:
            - 'db:db'
volumes:
    db_data:
